c_stdlib_version:        
  - "10.13"             # [osx and x86_64]
  - "11.0"              # [osx and arm64]
MACOSX_SDK_VERSION:        
  - "10.13"             # [osx and x86_64]
  - "11.0"              # [osx and arm64]
