MACOSX_DEPLOYMENT_TARGET:
  - "10.12"             # [osx and x86_64]
  - "11.0"              # [osx and arm64]
MACOSX_SDK_VERSION:        
  - "10.12"             # [osx and x86_64]
  - "11.0"              # [osx and arm64]
