{% set version = "4.1.0" %}

package:
  name: hurl
  version: {{ version }}

source:
  url: https://github.com/Orange-OpenSource/hurl/archive/{{ version }}.tar.gz
  sha256: 3356f64158e6dc5f2e29c37eee80a43332b1734baa7380356affeb5160ffca09

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - cargo-bundle-licenses
    - pkg-config
    - libxml2
  host:
    - libxml2
    - libcurl

test:
  commands:
    - hurl --version
    - hurlfmt --version
    - echo HEAD https://hurl.dev | hurl --include --no-color

about:
  home: https://hurl.dev
  summary: Run and Test HTTP Requests with plain text and curl
  description: |
    Hurl is a command line tool that runs HTTP requests defined in a simple plain text format.

    It can chain requests, capture values and evaluate queries on headers and body response. Hurl is very 
    versatile: it can be used for both fetching data and testing HTTP sessions.

    Hurl makes it easy to work with HTML content, REST / SOAP / GraphQL APIs, or any other XML / JSON based APIs.

  license: Apache-2.0
  license_family: Apache
  license_file: 
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://hurl.dev
  dev_url: https://github.com/Orange-OpenSource/hurl


extra:
  recipe-maintainers:
    - jcamiel
